In [66]:
import numpy as np
np.random.seed(42)  # seed for reproducibility

x0 = np.random.random_sample(size=6)  # One-dimensional array _float
x=np.random.random_integers(10, size=6)
x1=np.random.randint(10, size=6)     #  One-dimensional array _ integer
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

/Users/onion8/miniconda3/lib/python2.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  """


In [76]:
print("x3 ndim: ", x3.ndim)  #number of dimensions
print("x3 shape:", x3.shape) #each dim size
print("x3 size: ", x3.size)  #array size

('x3 ndim: ', 3)
('x3 shape:', (3, 4, 5))
('x3 size: ', 60)


In [82]:
#dtype of each array element
print("x0 dtype :", x0.dtype) 
print("x  dtype :", x.dtype)
print("x1 dtype :", x1.dtype)

('x0 dtype :', dtype('float64'))
('x  dtype :', dtype('int64'))
('x1 dtype :', dtype('int64'))


In [88]:
#byte size of each array element
print("x0 itemsize :", x0.itemsize, "bytes") 
print("x  itemsize :", x.itemsize, "bytes")
print("x1 itemsize :", x1.itemsize, "bytes")

('x0 itemsize :', 8, 'bytes')
('x  itemsize :', 8, 'bytes')
('x1 itemsize :', 8, 'bytes')


In [94]:
#byte size of array
print("x3 nbytes :", x3.nbytes, "bytes")

('x3 nbytes :', 480, 'bytes')


In [98]:
#accessing element from both sides in 1-D array
x1[4]==x1[-2]


True

In [100]:
#accessing multi-dimensional array by comma-separated tuple of indices 
x2[0, 0]

4

In [111]:
#accesing same element by negative indices
x2[0, 0]==x2[-3,-4]

True

In [112]:
#can be modified same way
x2[0, 0]=4.0

In [113]:
#here 4.0 is truncated to 4, why? (NumPy arrays have a fixed type)
x2

array([[4, 0, 9, 5],
       [8, 0, 9, 2],
       [6, 3, 8, 2]])

### x[start:stop:step] (Accessing sub arrays)

In [115]:
x1[:5] 

array([5, 4, 1, 7, 5])

In [116]:
x1[3:] 

array([7, 5, 1])

In [117]:
x1[4:6] 

array([5, 1])

In [119]:
x1[::2]  # every other element

array([5, 1, 5])

### In case of -ve step the defaults for start and stop are swapped

In [124]:
x1

array([5, 4, 1, 7, 5, 1])

In [134]:
x1[:]

array([5, 4, 1, 7, 5, 1])

In [121]:
x1[::-1]  # all elements, reversed

array([1, 5, 7, 1, 4, 5])

In [127]:
x1[4::-2]  # reversed every other from index 5

array([5, 1, 5])

## Accessing sub arrays of multi-dim array by comma separation

In [128]:
x2

array([[4, 0, 9, 5],
       [8, 0, 9, 2],
       [6, 3, 8, 2]])

In [129]:
x2[:2, :3]  # two rows, three columns

array([[4, 0, 9],
       [8, 0, 9]])

In [130]:
x2[:, ::2]  # all rows, every other column

array([[4, 9],
       [8, 9],
       [6, 8]])

In [135]:
x2[::-1, ::-1]

array([[2, 8, 3, 6],
       [2, 9, 0, 8],
       [5, 9, 0, 4]])

## Accessing single row and col(combining indexing and slicing)

In [138]:
x2[:,1]# second column of x2

array([0, 0, 3])

In [141]:
x2[2,:]# third column of x2

array([6, 3, 8, 2])

In [142]:
x2[2,:]==x2[2] #In the case of row access, the empty slice can be omitted for a more compact syntax:

array([ True,  True,  True,  True])

## Numpy array slices are view while list slices are copies

In [143]:
x2

array([[4, 0, 9, 5],
       [8, 0, 9, 2],
       [6, 3, 8, 2]])

In [147]:

x2_sub = x2[:2, :2]
(x2_sub)

array([[4, 0],
       [8, 0]])

In [158]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  0],
       [ 8,  0]])

In [159]:
x2

array([[99,  0,  9,  5],
       [ 8,  0,  9,  2],
       [ 6,  3,  8,  2]])

### This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### If you need the copies :

In [151]:
x2_sub_copy = x2[:2, :2].copy()
(x2_sub_copy)

array([[99,  0],
       [ 8,  0]])

In [161]:
x2_sub_copy[0, 0] = 30
x2_sub_copy

array([[30,  0],
       [ 8,  0]])

In [162]:
x2

array([[99,  0,  9,  5],
       [ 8,  0,  9,  2],
       [ 6,  3,  8,  2]])

## Reshaping

In [163]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Initial array must match the size of the reshaped array. It is a no-copy


## Row to col matrix

In [179]:
x=np.arange(9)

In [173]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [180]:
x.reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [181]:
x[:, np.newaxis] #similar to accessing single col or row where row/col is replaced by newaxis

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Concatenation of arrays

In [182]:

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [186]:
#more than 2 arrays
z = [99, 99]
(np.concatenate([x, y, z]))

array([ 1,  2,  3,  3,  2,  1, 99, 99])

In [187]:

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [188]:
# concatenate along the first axis
np.concatenate([grid, grid],axis=0) #Insert like row

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [190]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1) #Insert like column

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [192]:
np.concatenate([grid, z]) #not working with different dimensions

ValueError: all the input arrays must have same number of dimensions

In [193]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid]) # insert like rows

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [195]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y]) # insert like cols

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting arrays

In [205]:

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x,[2,3]) #mentioning split points
(x1, x2, x3)# values before split points goes into separate arrays

(array([1, 2]), array([3]), array([99, 99,  3,  2,  1]))

In [207]:

grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [210]:

upper, lower = np.vsplit(grid, [2])
print(upper)
print('----------')
print(lower)# split rows

[[0 1 2 3]
 [4 5 6 7]]
----------
[[ 8  9 10 11]
 [12 13 14 15]]


In [213]:
right, left = np.hsplit(grid, [2])
print(right)
print('-------')
print(left)# split rows

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
-------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
